name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Weather Service)
        env:
          WEATHER_SERVICE_OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          docker build --build-arg WEATHER_SERVICE_OPENWEATHERMAP_API_KEY=$WEATHER_SERVICE_OPENWEATHERMAP_API_KEY -t ${{ secrets.DOCKER_USERNAME }}/weather-service:latest -f ./weather-data-service/Dockerfile ./weather-data-service
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-service:latest

      - name: Build and push Docker image (User Preferences Service)
        env:
          USER_PREFERENCES_SERVICE_OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          docker build --build-arg USER_PREFERENCES_SERVICE_OPENWEATHERMAP_API_KEY=$USER_PREFERENCES_SERVICE_OPENWEATHERMAP_API_KEY -t ${{ secrets.DOCKER_USERNAME }}/user-preferences-service:latest -f ./user-preferences-service/Dockerfile ./user-preferences-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-preferences-service:latest

      - name: Build and push Docker image (User Notification Service)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-notification-service:latest ./user-notification-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-notification-service:latest



