name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (Weather Service)
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          docker build --build-arg OPENWEATHERMAP_API_KEY=$OPENWEATHERMAP_API_KEY -t ${{ secrets.DOCKER_HUB_USERNAME }}/weather-service:latest -f weather-data-service/Dockerfile ./weather-data-service
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-service:latest

      - name: Build and push Docker image (User Preferences Service)
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          docker build --build-arg OPENWEATHERMAP_API_KEY=$OPENWEATHERMAP_API_KEY -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-preferences-service:latest -f user-preferences-service/Dockerfile ./user-preferences-service
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-preferences-service:latest

      # Add similar steps for the third microservice as needed.

