
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (Weather Service)
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          cd weather-data-service
          docker build --build-arg OPENWEATHERMAP_API_KEY=$OPENWEATHERMAP_API_KEY -t ${{ secrets.DOCKER_HUB_USERNAME }}/weather-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-service:latest

      - name: Build and push Docker image (User Preferences Service)
        run: |
          cd user-preferences-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-preferences-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-preferences-service:latest

      - name: Build and push Docker image (User Notification Service)
        run: |
          cd user-notification-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-notification-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-notification-service:latest




