name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image (Weather Service)
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/weather-service:latest -f weather-data-service/Dockerfile ./weather-data-service
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-service:latest

    - name: Build and push Docker image (User Preferences Service)
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-preferences-service:latest -f user-preferences-service/Dockerfile ./user-preferences-service
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-preferences-service:latest

    - name: Build and push Docker image (User Notification Service)
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-notification-service:latest -f user-notification-service/Dockerfile ./user-notification-service
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-notification-service:latest
